Repository onlydustxyz/marketplace-frontend, pull requests merged in 2022-08, with the labels that each got.

#113 :sparkles: Find contributor by id (dummy implem)
  Cargo.lock
  Cargo.toml
  src/application/get_contributor.rs
  src/application/mod.rs
  src/domain/entities/contributor.rs
  src/domain/errors.rs
  src/domain/repositories/contributor.rs
  src/domain/repositories/mod.rs
  src/infrastructure/database/contributor_repository.rs
  src/infrastructure/database/mod.rs
  src/lib.rs
  src/main.rs
  src/routes/contributions.rs
  src/routes/contributors/dto.rs
  src/routes/contributors/find.rs
  src/routes/contributors/mod.rs
  src/routes/mod.rs
  src/starknet/contracts/registry.rs
Labels: Context: isolated, Type: feature, Duration: few days, Techno: rust, Difficulty: intermediate, State: review

#114 :recycle: database client manages its own connection pool
  src/action_queue/mod.rs
  src/application/get_contributor.rs
  src/application/mod.rs
  src/application/tests/apply_to_contribution.rs
  src/application/tests/mod.rs
  src/domain/repositories/application.rs
  src/infrastructure/database/connection.rs
  src/infrastructure/database/error.rs
  src/infrastructure/database/mod.rs
  src/infrastructure/database/repositories/application.rs
  src/infrastructure/database/repositories/contribution.rs
  src/infrastructure/database/repositories/contributor.rs
  src/infrastructure/database/repositories/mod.rs
  src/infrastructure/database/repositories/project.rs
  src/main.rs
  src/routes/contributions/apply.rs
  src/routes/projects/mod.rs
Labels: Duration: under a day, Type: refactor, Difficulty: easy, Context: isolated, Techno: rust, State: review

#116 :ambulance: Fix unmanaged database state
  src/application/get_contributor.rs
  src/routes/contributions/apply.rs
  src/routes/projects/mod.rs
Labels: Type: bug, Duration: under a day, Difficulty: easy, Context: isolated, Techno: rust, State: review

#120 :recycle: move action queue dequeuer in starknet module
  src/infrastructure/starknet/action_queue/mod.rs
  src/infrastructure/starknet/mod.rs
  src/main.rs
Labels: Duration: under a day, Type: refactor, Context: isolated, Techno: rust, Difficulty: intermediate, State: review

#121 :bug: spawn blockchain actions in child thread to handle panics
  src/infrastructure/starknet/mod.rs
  src/infrastructure/starknet/services/contribution.rs
Labels: Type: bug, Duration: under a day, Difficulty: easy, Context: isolated, Techno: rust, State: review

#123 :sparkles: add local devnet support
  .env.example
  README.md
  scripts/docker/dev/docker-compose.yml
  src/infrastructure/starknet/mod.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: documentation, Type: feature, Techno: rust, State: review

#125 :sparkles: support 2d nonce account and make parallel transaction calls
  Cargo.lock
  Cargo.toml
  src/infrastructure/starknet/action_queue/mod.rs
  src/infrastructure/starknet/contracts/utils/contract_administrator.rs
  src/infrastructure/starknet/error.rs
  src/infrastructure/starknet/mod.rs
  src/infrastructure/starknet/services/contribution.rs
  src/infrastructure/starknet/transaction_processor/dequeuer.rs
  src/infrastructure/starknet/transaction_processor/mod.rs
Labels: Duration: under a day, Type: refactor, Difficulty: easy, Type: feature, Context: coupled, Techno: rust, State: review

#129 ♻️ enhance error management in starknet module
  src/infrastructure/starknet/contracts/error.rs
  src/infrastructure/starknet/contracts/utils/contract_administrator.rs
  src/infrastructure/starknet/contracts/utils/contract_viewer.rs
  src/infrastructure/starknet/contracts/utils/mod.rs
  src/infrastructure/starknet/error.rs
  src/routes/dto/to_http_api_problem.rs
Labels: Duration: under a day, Type: refactor, Difficulty: easy, Context: isolated, Techno: rust, State: review

#132 ✨ Local logging in terminal
  Cargo.lock
  Cargo.toml
  src/infrastructure/starknet/contracts/utils/contract_administrator.rs
  src/main.rs
Labels: Type: feature, Techno: rust

#133 👷 run starknet-devnet in a docker container
  .github/workflows/tests_e2e.yml
  scripts/docker/dev/docker-compose.yml
  scripts/docker/dev/starknet-devnet.Dockerfile
Labels: Duration: under a day, Type: build, Difficulty: easy, Context: isolated, State: review, Techno: docker

#137 :white_check_mark: add assign/validate contribution in e2e test
  src/bin/contribution/add.rs
  src/bin/contribution/assign.rs
  src/bin/contribution/mod.rs
  src/bin/contribution/validate.rs
  src/bin/e2e_tests.rs
  src/bin/projects/add.rs
  src/bin/projects/list.rs
  src/bin/utils/mod.rs
  src/data/contributions_assigned.json
  src/data/contributions_open.json
  src/data/contributions_validated.json
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Techno: rust, Type: test, State: review

#139 tests: use dto types in e2e testing
  src/bin/e2e_tests.rs
  src/bin/projects/list.rs
  src/bin/utils/mod.rs
  src/dto/mod.rs
  src/dto/project.rs
  src/lib.rs
  src/routes/projects/mod.rs
Labels: Type: refactor, Techno: rust, Type: test, State: review
