Repository onlydustxyz/marketplace-frontend, pull requests merged in 2022-07, with the labels that each got.

#30 :sparkles: store transaction hash in database after updating smart contract
  Cargo.lock
  Cargo.toml
  migrations/2022-06-14-104536_create_pull_requests/up.sql
  src/bin/add_repo.rs
  src/bin/index_repos.rs
  src/database/models.rs
  src/database/schema.rs
  src/starknet/mod.rs
  src/starknet/models.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: feature, Techno: rust, State: review

#34 👷 add docker github workflow
  .github/workflows/docker.yml
Labels: Duration: under a day, Type: build, Difficulty: easy, Context: isolated, Techno: docker

#37 :recycle: rename and restructure modules to respect ubiquitous language
  migrations/2022-06-01-110904_create_projects/up.sql
  migrations/2022-06-14-104536_create_contributions/down.sql
  migrations/2022-06-14-104536_create_contributions/up.sql
  migrations/2022-06-14-104536_create_pull_requests/down.sql
  src/bin/add_repo.rs
  src/bin/index_repos.rs
  src/bin/upload_pr.rs
  src/database/mod.rs
  src/database/model.rs
  src/database/models.rs
  src/database/schema.rs
  src/domain/contribution.rs
  src/domain/fetcher.rs
  src/domain/logger.rs
  src/domain/mod.rs
  src/domain/on_chain.rs
  src/domain/project.rs
  src/github/mod.rs
  src/github/models.rs
  src/lib.rs
  src/main.rs
  src/model/mod.rs
  src/starknet/github_oracle.rs
  src/starknet/mod.rs
  src/utils/mod.rs
  src/utils/stream.rs
Labels: Duration: under a day, Type: refactor, Difficulty: easy, Context: intricated, Techno: rust, State: review

#38 :green_heart: fix clippy warnings + run CI for PR from forks
  .github/workflows/main.yml
  src/database/mod.rs
  src/domain/contribution.rs
  src/domain/project.rs
  src/starknet/github_oracle.rs
  src/starknet/registry.rs
Labels: Duration: under a day, Type: build, Difficulty: easy, Context: isolated, Techno: rust, State: review

#40 :memo: update README and .env.example with latest changes
  .env.example
  README.md
  src/bin/add_project.rs
  src/bin/index_projects.rs
  src/bin/upload_contributions.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: documentation, Techno: rust, State: review

#41 :recycle: move Oracle API into domain
  src/domain/on_chain.rs
  src/starknet/github_oracle.rs
  src/starknet/mod.rs
Labels: Duration: under a day, Type: refactor, Difficulty: easy, Context: isolated, Techno: rust, State: review

#44 ✨ add CORS and health-check handling
  src/main.rs
  src/routes/cors.rs
  src/routes/health.rs
  src/routes/mod.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: feature, Techno: rust

#45 👷 update docker repositories to fit the renaming
  .github/workflows/docker.yml
Labels: Duration: under a day, Type: build, Difficulty: easy, Context: isolated, Techno: docker

#53 :zap: use our own RPC node to perform contract calls
  .env.example
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Techno: rust, Type: performance, State: review

#52 :sparkles: wait for transaction to be accepted before sending a new one
  src/starknet/contract_administrator.rs
  src/starknet/domain_implementation/contributions.rs
  src/starknet/mod.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: feature, Techno: rust, State: review

#55 :sparkles: add all contribution flows from latest smart contract ABI
  .env.example
  src/database/models/actions.rs
  src/database/models/mod.rs
  src/domain/actions.rs
  src/domain/mod.rs
  src/domain/types/contributor.rs
  src/starknet/domain_implementation/contributions.rs
  src/starknet/mod.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: feature, Techno: rust, State: review

#75 :sparkles: fetch github data in GET /projects
  .env.example
  src/github/mod.rs
  src/main.rs
  src/routes/projects.rs
  src/starknet/registry.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: feature, Techno: rust, State: review

#84 ⚡️ Cache github result to avoid facing rate limits
  Cargo.lock
  Cargo.toml
  src/github/issue_cache.rs
  src/github/mod.rs
  src/github/repo_cache.rs
  src/main.rs
  src/routes/projects.rs
  src/utils/cache.rs
  src/utils/mod.rs
Labels: Duration: under a day, Context: isolated, Techno: rust, Type: performance, Difficulty: intermediate, State: review

#85 🐛 Add API_URL in .env.example
  .env.example
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: documentation, Techno: rust, State: review

#86 :bug: Fix contributor id parsing in REST API
  src/routes/contributions.rs
  src/routes/projects.rs
  src/starknet/contract_administrator.rs
Labels: Type: bug, Duration: under a day, Difficulty: easy, Context: isolated, Techno: rust, State: review

#89 :bug: fix user information fetching from registry smart contract
  src/domain/traits/contracts_interface.rs
  src/domain/types/contributor.rs
  src/github/mod.rs
  src/github/user_cache.rs
  src/main.rs
  src/routes/projects.rs
  src/starknet/domain_implementation/mod.rs
  src/starknet/domain_implementation/profile.rs
  src/starknet/domain_implementation/registry.rs
  src/starknet/mod.rs
Labels: Type: bug, Duration: under a day, Difficulty: easy, Context: isolated, Techno: rust, State: review

#91 feat(ProjectAPI): remove querying smart contract for user eligibility
  src/domain/traits/contracts_interface.rs
  src/routes/projects.rs
  src/starknet/domain_implementation/contributions.rs
  src/starknet/mod.rs
Labels: Duration: under a day, Difficulty: easy, Context: isolated, Type: feature, State: review

#92 ⚡️ cache contributors data
  src/domain/types/contributor.rs
  src/github/mod.rs
  src/github/user_cache.rs
  src/main.rs
  src/routes/contributor_cache.rs
  src/routes/mod.rs
  src/routes/projects.rs
Labels: Duration: under a day, Difficulty: easy, Context: coupled, Techno: rust, Type: performance

#95 refacrtor(ProjectRoutes): split struct and routes in two files
  src/routes/projects/dto.rs
  src/routes/projects/mod.rs
Labels: Type: refactor, Difficulty: easy, Context: isolated

#96 perf(ProjectAPI): parallelize contribution building inside a project …
  Cargo.toml
  src/github/issue_cache.rs
  src/routes/contributor_cache.rs
  src/routes/projects/mod.rs
  src/utils/cache.rs
Labels: Context: isolated, Type: performance, Difficulty: intermediate

#98 refactor(caches): move all caches into the same module
  src/github/mod.rs
  src/main.rs
  src/routes/mod.rs
  src/routes/projects/mod.rs
  src/utils/caches/contributor_cache.rs
  src/utils/caches/issue_cache.rs
  src/utils/caches/mod.rs
  src/utils/caches/repo_cache.rs
  src/utils/mod.rs
Labels: Type: refactor, Difficulty: easy, Context: isolated

#104 :construction: refactor starknet module
  src/action_queue/mod.rs
  src/domain/errors.rs
  src/domain/mod.rs
  src/domain/services/contribution.rs
  src/domain/services/mod.rs
  src/starknet/contracts/contributions.rs
  src/starknet/contracts/mod.rs
  src/starknet/contracts/profile.rs
  src/starknet/contracts/registry.rs
  src/starknet/contracts/utils/contract_administrator.rs
  src/starknet/contracts/utils/contract_viewer.rs
  src/starknet/contracts/utils/mod.rs
  src/starknet/domain_implementation/mod.rs
  src/starknet/mod.rs
Labels: Duration: under a day, Type: refactor, Difficulty: easy, Context: coupled, Techno: rust, State: review
